language: python
python:
  - "2.7"
# command to install dependencies
install:
  - wget https://github.com/sympy/sympy/archive/master.zip && unzip master.zip && pip install ./sympy-master
  - wget https://github.com/tclose/nineml-python/archive/develop.zip
  - unzip develop.zip
  - pip install ./nineml-python-develop 
  - pip install coveralls --use-mirrors
# command to run tests, e.g. python setup.py test
script:
  nosetests test --with-coverage --cover-package=ninemlcatalog
after_success:
  coveralls
