language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install git+git://github.com/sympy/sympy.git@master
  - pip install git+git://github.com/tclose/nineml-python.git@serialization
  - pip install coveralls --use-mirrors
# command to run tests, e.g. python setup.py test
script:
  nosetests test --with-coverage --cover-package=ninemlcatalog
after_success:
  coveralls
